openapi: 3.0.1
info:
  title: TodosAPI
  description: API Definition of TodosAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/emp
paths:
  /todos:
    get:
      responses:
        default:
          description: Default response
